[2024-08-16 10:57:50,284] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-08-16 10:57:50,290] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-08-16 10:57:50,290] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:57:50,290] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 10:57:50,290] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:57:50,310] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-17 00:00:00+00:00
[2024-08-16 10:57:50,317] {standard_task_runner.py:52} INFO - Started process 58782 to run task
[2024-08-16 10:57:50,320] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp7xmk4b8d', '--error-file', '/tmp/tmpiikokybj']
[2024-08-16 10:57:50,321] {standard_task_runner.py:80} INFO - Job 192: Subtask extract_clima_files
[2024-08-16 10:57:50,365] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 10:57:50,389] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 10:57:50,394] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240617T000000, start_date=20240816T135750, end_date=20240816T135750
[2024-08-16 10:57:50,401] {standard_task_runner.py:92} ERROR - Failed to execute job 192 for task extract_clima_files ('data_inteval_end' is undefined; 58782)
[2024-08-16 10:57:50,417] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 10:57:50,431] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:13:56,712] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-08-16 11:13:56,717] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-08-16 11:13:56,717] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:13:56,717] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:13:56,717] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:13:56,729] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-17 00:00:00+00:00
[2024-08-16 11:13:56,732] {standard_task_runner.py:52} INFO - Started process 65993 to run task
[2024-08-16 11:13:56,735] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpxyj7d_na', '--error-file', '/tmp/tmp9dk_cs5e']
[2024-08-16 11:13:56,735] {standard_task_runner.py:80} INFO - Job 214: Subtask extract_clima_files
[2024-08-16 11:13:56,777] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:13:56,799] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 11:13:56,804] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240617T000000, start_date=20240816T141356, end_date=20240816T141356
[2024-08-16 11:13:56,813] {standard_task_runner.py:92} ERROR - Failed to execute job 214 for task extract_clima_files ('data_inteval_end' is undefined; 65993)
[2024-08-16 11:13:56,829] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 11:13:56,850] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:18:56,777] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-08-16 11:18:56,784] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-08-16 11:18:56,784] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:18:56,784] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:18:56,784] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:18:56,802] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-17 00:00:00+00:00
[2024-08-16 11:18:56,804] {standard_task_runner.py:52} INFO - Started process 68979 to run task
[2024-08-16 11:18:56,807] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp7kdwiflr', '--error-file', '/tmp/tmp0_e6zv9m']
[2024-08-16 11:18:56,807] {standard_task_runner.py:80} INFO - Job 216: Subtask extract_clima_files
[2024-08-16 11:18:56,844] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:18:56,891] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-06-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-17T00:00:00+00:00
[2024-08-16 11:18:56,893] {logging_mixin.py:115} INFO - 2024-06-24
[2024-08-16 11:18:57,642] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:18:57,648] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240617T000000, start_date=20240816T141856, end_date=20240816T141857
[2024-08-16 11:18:57,674] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:18:57,686] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:21:57,658] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-08-16 11:21:57,664] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-08-16 11:21:57,664] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:21:57,664] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:21:57,664] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:21:57,676] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-17 00:00:00+00:00
[2024-08-16 11:21:57,679] {standard_task_runner.py:52} INFO - Started process 72713 to run task
[2024-08-16 11:21:57,682] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp81s8q3g4', '--error-file', '/tmp/tmpxxm2_3_q']
[2024-08-16 11:21:57,682] {standard_task_runner.py:80} INFO - Job 218: Subtask extract_clima_files
[2024-08-16 11:21:57,738] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-17T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:21:57,789] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-06-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-17T00:00:00+00:00
[2024-08-16 11:21:57,790] {logging_mixin.py:115} INFO - 2024-06-24
[2024-08-16 11:21:58,491] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:21:58,500] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240617T000000, start_date=20240816T142157, end_date=20240816T142158
[2024-08-16 11:21:58,545] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:21:58,568] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
