[2024-08-16 10:58:06,136] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-08-16 10:58:06,144] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-08-16 10:58:06,144] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:58:06,144] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 10:58:06,145] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:58:06,158] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-15 00:00:00+00:00
[2024-08-16 10:58:06,162] {standard_task_runner.py:52} INFO - Started process 59086 to run task
[2024-08-16 10:58:06,165] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp0fxt7qj5', '--error-file', '/tmp/tmpapreqtz5']
[2024-08-16 10:58:06,165] {standard_task_runner.py:80} INFO - Job 199: Subtask extract_clima_files
[2024-08-16 10:58:06,209] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 10:58:06,234] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 10:58:06,238] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240715T000000, start_date=20240816T135806, end_date=20240816T135806
[2024-08-16 10:58:06,248] {standard_task_runner.py:92} ERROR - Failed to execute job 199 for task extract_clima_files ('data_inteval_end' is undefined; 59086)
[2024-08-16 10:58:06,259] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 10:58:06,280] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:14:10,154] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-08-16 11:14:10,160] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-08-16 11:14:10,160] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:10,160] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:14:10,160] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:10,170] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-15 00:00:00+00:00
[2024-08-16 11:14:10,173] {standard_task_runner.py:52} INFO - Started process 66260 to run task
[2024-08-16 11:14:10,176] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmph310h4oo', '--error-file', '/tmp/tmpqwvskkki']
[2024-08-16 11:14:10,177] {standard_task_runner.py:80} INFO - Job 221: Subtask extract_clima_files
[2024-08-16 11:14:10,221] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:14:10,240] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 11:14:10,246] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240715T000000, start_date=20240816T141410, end_date=20240816T141410
[2024-08-16 11:14:10,258] {standard_task_runner.py:92} ERROR - Failed to execute job 221 for task extract_clima_files ('data_inteval_end' is undefined; 66260)
[2024-08-16 11:14:10,270] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 11:14:10,288] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:19:13,499] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-08-16 11:19:13,505] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-08-16 11:19:13,505] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:13,505] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:19:13,505] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:13,514] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-15 00:00:00+00:00
[2024-08-16 11:19:13,518] {standard_task_runner.py:52} INFO - Started process 69257 to run task
[2024-08-16 11:19:13,521] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpk9xo355r', '--error-file', '/tmp/tmpp_ir5jdu']
[2024-08-16 11:19:13,521] {standard_task_runner.py:80} INFO - Job 223: Subtask extract_clima_files
[2024-08-16 11:19:13,554] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:19:13,598] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-07-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-15T00:00:00+00:00
[2024-08-16 11:19:13,600] {logging_mixin.py:115} INFO - 2024-07-22
[2024-08-16 11:19:14,315] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:19:14,324] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240715T000000, start_date=20240816T141913, end_date=20240816T141914
[2024-08-16 11:19:14,345] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:19:14,361] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:22:14,817] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-08-16 11:22:14,822] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-08-16 11:22:14,822] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:14,822] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:22:14,822] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:14,830] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-15 00:00:00+00:00
[2024-08-16 11:22:14,833] {standard_task_runner.py:52} INFO - Started process 73058 to run task
[2024-08-16 11:22:14,835] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpw35p9nb4', '--error-file', '/tmp/tmpz1o7f6o8']
[2024-08-16 11:22:14,836] {standard_task_runner.py:80} INFO - Job 225: Subtask extract_clima_files
[2024-08-16 11:22:14,867] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-15T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:22:14,902] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-07-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-15T00:00:00+00:00
[2024-08-16 11:22:14,903] {logging_mixin.py:115} INFO - 2024-07-22
[2024-08-16 11:22:15,578] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:22:15,585] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240715T000000, start_date=20240816T142214, end_date=20240816T142215
[2024-08-16 11:22:15,618] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:22:15,631] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
