[2024-08-16 10:58:03,967] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-08-16 10:58:03,975] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-08-16 10:58:03,975] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:58:03,975] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 10:58:03,975] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:58:03,987] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-08 00:00:00+00:00
[2024-08-16 10:58:03,997] {standard_task_runner.py:52} INFO - Started process 59046 to run task
[2024-08-16 10:58:04,000] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpvwqvt1tk', '--error-file', '/tmp/tmpkjby8k34']
[2024-08-16 10:58:04,000] {standard_task_runner.py:80} INFO - Job 198: Subtask extract_clima_files
[2024-08-16 10:58:04,045] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 10:58:04,067] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 10:58:04,073] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240708T000000, start_date=20240816T135803, end_date=20240816T135804
[2024-08-16 10:58:04,084] {standard_task_runner.py:92} ERROR - Failed to execute job 198 for task extract_clima_files ('data_inteval_end' is undefined; 59046)
[2024-08-16 10:58:04,094] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 10:58:04,109] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:14:08,282] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-08-16 11:14:08,287] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-08-16 11:14:08,287] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:08,287] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:14:08,287] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:08,296] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-08 00:00:00+00:00
[2024-08-16 11:14:08,299] {standard_task_runner.py:52} INFO - Started process 66214 to run task
[2024-08-16 11:14:08,303] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpyshk6899', '--error-file', '/tmp/tmpy3d2m54c']
[2024-08-16 11:14:08,303] {standard_task_runner.py:80} INFO - Job 220: Subtask extract_clima_files
[2024-08-16 11:14:08,349] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:14:08,370] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 11:14:08,375] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240708T000000, start_date=20240816T141408, end_date=20240816T141408
[2024-08-16 11:14:08,388] {standard_task_runner.py:92} ERROR - Failed to execute job 220 for task extract_clima_files ('data_inteval_end' is undefined; 66214)
[2024-08-16 11:14:08,397] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 11:14:08,419] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:19:10,961] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-08-16 11:19:10,968] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-08-16 11:19:10,968] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:10,968] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:19:10,968] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:10,978] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-08 00:00:00+00:00
[2024-08-16 11:19:10,980] {standard_task_runner.py:52} INFO - Started process 69239 to run task
[2024-08-16 11:19:10,982] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpm_poray7', '--error-file', '/tmp/tmpzu3nzrn6']
[2024-08-16 11:19:10,983] {standard_task_runner.py:80} INFO - Job 222: Subtask extract_clima_files
[2024-08-16 11:19:11,016] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:19:11,056] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-07-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-08T00:00:00+00:00
[2024-08-16 11:19:11,056] {logging_mixin.py:115} INFO - 2024-07-15
[2024-08-16 11:19:11,733] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:19:11,740] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240708T000000, start_date=20240816T141910, end_date=20240816T141911
[2024-08-16 11:19:11,763] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:19:11,776] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:22:12,376] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-08-16 11:22:12,381] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [queued]>
[2024-08-16 11:22:12,381] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:12,381] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:22:12,381] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:12,391] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-08 00:00:00+00:00
[2024-08-16 11:22:12,394] {standard_task_runner.py:52} INFO - Started process 72984 to run task
[2024-08-16 11:22:12,397] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-08T00:00:00+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpcsmi52bq', '--error-file', '/tmp/tmpigh1t_ed']
[2024-08-16 11:22:12,397] {standard_task_runner.py:80} INFO - Job 224: Subtask extract_clima_files
[2024-08-16 11:22:12,437] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-08T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:22:12,485] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-07-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-08T00:00:00+00:00
[2024-08-16 11:22:12,486] {logging_mixin.py:115} INFO - 2024-07-15
[2024-08-16 11:22:13,193] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:22:13,200] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240708T000000, start_date=20240816T142212, end_date=20240816T142213
[2024-08-16 11:22:13,216] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:22:13,228] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
