[2024-08-16 10:58:13,951] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-08-16 10:58:13,966] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-08-16 10:58:13,966] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:58:13,966] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 10:58:13,966] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:58:13,987] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-22 00:00:00+00:00
[2024-08-16 10:58:13,993] {standard_task_runner.py:52} INFO - Started process 59228 to run task
[2024-08-16 10:58:13,998] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-22T00:00:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp2avndapn', '--error-file', '/tmp/tmprgos0gla']
[2024-08-16 10:58:13,998] {standard_task_runner.py:80} INFO - Job 202: Subtask extract_clima_files
[2024-08-16 10:58:14,106] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 10:58:14,151] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 10:58:14,157] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240722T000000, start_date=20240816T135813, end_date=20240816T135814
[2024-08-16 10:58:14,172] {standard_task_runner.py:92} ERROR - Failed to execute job 202 for task extract_clima_files ('data_inteval_end' is undefined; 59228)
[2024-08-16 10:58:14,188] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 10:58:14,212] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:14:16,522] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-08-16 11:14:16,528] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-08-16 11:14:16,529] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:16,529] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:14:16,529] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:16,542] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-22 00:00:00+00:00
[2024-08-16 11:14:16,544] {standard_task_runner.py:52} INFO - Started process 66369 to run task
[2024-08-16 11:14:16,547] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-22T00:00:00+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmphs7uc26p', '--error-file', '/tmp/tmpamks3_3h']
[2024-08-16 11:14:16,547] {standard_task_runner.py:80} INFO - Job 224: Subtask extract_clima_files
[2024-08-16 11:14:16,583] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:14:16,602] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 11:14:16,607] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240722T000000, start_date=20240816T141416, end_date=20240816T141416
[2024-08-16 11:14:16,614] {standard_task_runner.py:92} ERROR - Failed to execute job 224 for task extract_clima_files ('data_inteval_end' is undefined; 66369)
[2024-08-16 11:14:16,641] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 11:14:16,655] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:19:20,509] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-08-16 11:19:20,513] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-08-16 11:19:20,513] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:20,513] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:19:20,513] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:20,522] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-22 00:00:00+00:00
[2024-08-16 11:19:20,525] {standard_task_runner.py:52} INFO - Started process 69410 to run task
[2024-08-16 11:19:20,527] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-22T00:00:00+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp5zgz5hzv', '--error-file', '/tmp/tmpws_ho5kf']
[2024-08-16 11:19:20,528] {standard_task_runner.py:80} INFO - Job 226: Subtask extract_clima_files
[2024-08-16 11:19:20,568] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:19:20,609] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-07-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-22T00:00:00+00:00
[2024-08-16 11:19:20,610] {logging_mixin.py:115} INFO - 2024-07-29
[2024-08-16 11:19:21,303] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:19:21,311] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240722T000000, start_date=20240816T141920, end_date=20240816T141921
[2024-08-16 11:19:21,351] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:19:21,362] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:22:21,429] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-08-16 11:22:21,434] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [queued]>
[2024-08-16 11:22:21,435] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:21,435] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:22:21,435] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:21,446] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-22 00:00:00+00:00
[2024-08-16 11:22:21,448] {standard_task_runner.py:52} INFO - Started process 73190 to run task
[2024-08-16 11:22:21,451] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-22T00:00:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp_psyuzdc', '--error-file', '/tmp/tmplvyu61ed']
[2024-08-16 11:22:21,451] {standard_task_runner.py:80} INFO - Job 228: Subtask extract_clima_files
[2024-08-16 11:22:21,481] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-22T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:22:21,512] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-07-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-22T00:00:00+00:00
[2024-08-16 11:22:21,513] {logging_mixin.py:115} INFO - 2024-07-29
[2024-08-16 11:22:22,420] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:22:22,428] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240722T000000, start_date=20240816T142221, end_date=20240816T142222
[2024-08-16 11:22:22,454] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:22:22,466] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
