[2024-08-16 10:57:52,033] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-08-16 10:57:52,038] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-08-16 10:57:52,038] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:57:52,038] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 10:57:52,038] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:57:52,050] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-24 00:00:00+00:00
[2024-08-16 10:57:52,053] {standard_task_runner.py:52} INFO - Started process 58850 to run task
[2024-08-16 10:57:52,056] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpkn6wifuy', '--error-file', '/tmp/tmpqm83zqsi']
[2024-08-16 10:57:52,057] {standard_task_runner.py:80} INFO - Job 193: Subtask extract_clima_files
[2024-08-16 10:57:52,098] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 10:57:52,120] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 10:57:52,126] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240624T000000, start_date=20240816T135752, end_date=20240816T135752
[2024-08-16 10:57:52,134] {standard_task_runner.py:92} ERROR - Failed to execute job 193 for task extract_clima_files ('data_inteval_end' is undefined; 58850)
[2024-08-16 10:57:52,149] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 10:57:52,165] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:13:58,419] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-08-16 11:13:58,424] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-08-16 11:13:58,424] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:13:58,424] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:13:58,425] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:13:58,436] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-24 00:00:00+00:00
[2024-08-16 11:13:58,441] {standard_task_runner.py:52} INFO - Started process 66030 to run task
[2024-08-16 11:13:58,445] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpvatnot22', '--error-file', '/tmp/tmpxpil5exb']
[2024-08-16 11:13:58,445] {standard_task_runner.py:80} INFO - Job 215: Subtask extract_clima_files
[2024-08-16 11:13:58,480] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:13:58,499] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 11:13:58,503] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240624T000000, start_date=20240816T141358, end_date=20240816T141358
[2024-08-16 11:13:58,511] {standard_task_runner.py:92} ERROR - Failed to execute job 215 for task extract_clima_files ('data_inteval_end' is undefined; 66030)
[2024-08-16 11:13:58,540] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 11:13:58,554] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:18:59,395] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-08-16 11:18:59,402] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-08-16 11:18:59,403] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:18:59,403] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:18:59,403] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:18:59,413] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-24 00:00:00+00:00
[2024-08-16 11:18:59,416] {standard_task_runner.py:52} INFO - Started process 69020 to run task
[2024-08-16 11:18:59,420] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpr88vckw8', '--error-file', '/tmp/tmph1c_p8sa']
[2024-08-16 11:18:59,427] {standard_task_runner.py:80} INFO - Job 217: Subtask extract_clima_files
[2024-08-16 11:18:59,467] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:18:59,518] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-06-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-24T00:00:00+00:00
[2024-08-16 11:18:59,519] {logging_mixin.py:115} INFO - 2024-07-01
[2024-08-16 11:19:00,273] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:19:00,279] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240624T000000, start_date=20240816T141859, end_date=20240816T141900
[2024-08-16 11:19:00,323] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:19:00,336] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:22:00,429] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-08-16 11:22:00,435] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-08-16 11:22:00,436] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:00,436] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:22:00,436] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:00,452] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-24 00:00:00+00:00
[2024-08-16 11:22:00,455] {standard_task_runner.py:52} INFO - Started process 72786 to run task
[2024-08-16 11:22:00,457] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '219', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpmxidak77', '--error-file', '/tmp/tmptsh0sfp7']
[2024-08-16 11:22:00,458] {standard_task_runner.py:80} INFO - Job 219: Subtask extract_clima_files
[2024-08-16 11:22:00,501] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-24T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:22:00,567] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-06-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-24T00:00:00+00:00
[2024-08-16 11:22:00,569] {logging_mixin.py:115} INFO - 2024-07-01
[2024-08-16 11:22:01,358] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:22:01,365] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240624T000000, start_date=20240816T142200, end_date=20240816T142201
[2024-08-16 11:22:01,404] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:22:01,417] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
