[2024-08-16 10:57:45,984] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-08-16 10:57:45,988] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-08-16 10:57:45,988] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:57:45,988] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 10:57:45,988] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:57:45,999] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-10 00:00:00+00:00
[2024-08-16 10:57:46,002] {standard_task_runner.py:52} INFO - Started process 58719 to run task
[2024-08-16 10:57:46,004] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpvq7olojd', '--error-file', '/tmp/tmp2npbqvrg']
[2024-08-16 10:57:46,005] {standard_task_runner.py:80} INFO - Job 190: Subtask extract_clima_files
[2024-08-16 10:57:46,038] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 10:57:46,067] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 10:57:46,071] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240610T000000, start_date=20240816T135745, end_date=20240816T135746
[2024-08-16 10:57:46,079] {standard_task_runner.py:92} ERROR - Failed to execute job 190 for task extract_clima_files ('data_inteval_end' is undefined; 58719)
[2024-08-16 10:57:46,110] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 10:57:46,136] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:13:53,337] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-08-16 11:13:53,343] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-08-16 11:13:53,343] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:13:53,343] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:13:53,343] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:13:53,351] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-10 00:00:00+00:00
[2024-08-16 11:13:53,354] {standard_task_runner.py:52} INFO - Started process 65937 to run task
[2024-08-16 11:13:53,357] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpn5pmrhtu', '--error-file', '/tmp/tmpyhoqo71t']
[2024-08-16 11:13:53,357] {standard_task_runner.py:80} INFO - Job 212: Subtask extract_clima_files
[2024-08-16 11:13:53,394] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:13:53,421] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 11:13:53,425] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240610T000000, start_date=20240816T141353, end_date=20240816T141353
[2024-08-16 11:13:53,437] {standard_task_runner.py:92} ERROR - Failed to execute job 212 for task extract_clima_files ('data_inteval_end' is undefined; 65937)
[2024-08-16 11:13:53,451] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 11:13:53,468] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:18:52,275] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-08-16 11:18:52,280] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-08-16 11:18:52,281] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:18:52,281] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:18:52,281] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:18:52,292] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-10 00:00:00+00:00
[2024-08-16 11:18:52,295] {standard_task_runner.py:52} INFO - Started process 68895 to run task
[2024-08-16 11:18:52,298] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmppt479yss', '--error-file', '/tmp/tmpc1nyl7fu']
[2024-08-16 11:18:52,299] {standard_task_runner.py:80} INFO - Job 214: Subtask extract_clima_files
[2024-08-16 11:18:52,331] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:18:52,391] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-06-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-10T00:00:00+00:00
[2024-08-16 11:18:52,392] {logging_mixin.py:115} INFO - 2024-06-17
[2024-08-16 11:18:53,254] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:18:53,260] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240610T000000, start_date=20240816T141852, end_date=20240816T141853
[2024-08-16 11:18:53,289] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:18:53,304] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:21:53,293] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-08-16 11:21:53,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [queued]>
[2024-08-16 11:21:53,300] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:21:53,300] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:21:53,300] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:21:53,309] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-06-10 00:00:00+00:00
[2024-08-16 11:21:53,312] {standard_task_runner.py:52} INFO - Started process 72651 to run task
[2024-08-16 11:21:53,315] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-06-10T00:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpapl7c061', '--error-file', '/tmp/tmpw5iebaph']
[2024-08-16 11:21:53,316] {standard_task_runner.py:80} INFO - Job 216: Subtask extract_clima_files
[2024-08-16 11:21:53,363] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-06-10T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:21:53,420] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-06-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-10T00:00:00+00:00
[2024-08-16 11:21:53,422] {logging_mixin.py:115} INFO - 2024-06-17
[2024-08-16 11:21:54,173] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:21:54,180] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240610T000000, start_date=20240816T142153, end_date=20240816T142154
[2024-08-16 11:21:54,220] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:21:54,234] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
