[2024-08-16 10:58:18,772] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-08-16 10:58:18,782] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-08-16 10:58:18,783] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:58:18,783] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 10:58:18,783] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:58:18,801] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-29 00:00:00+00:00
[2024-08-16 10:58:18,807] {standard_task_runner.py:52} INFO - Started process 59322 to run task
[2024-08-16 10:58:18,813] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-29T00:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpix6ys4rv', '--error-file', '/tmp/tmpabe8obcg']
[2024-08-16 10:58:18,814] {standard_task_runner.py:80} INFO - Job 204: Subtask extract_clima_files
[2024-08-16 10:58:18,864] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 10:58:18,888] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 10:58:18,894] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240729T000000, start_date=20240816T135818, end_date=20240816T135818
[2024-08-16 10:58:18,908] {standard_task_runner.py:92} ERROR - Failed to execute job 204 for task extract_clima_files ('data_inteval_end' is undefined; 59322)
[2024-08-16 10:58:18,915] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 10:58:18,930] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:14:19,911] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-08-16 11:14:19,916] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-08-16 11:14:19,916] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:19,916] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:14:19,916] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:19,929] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-29 00:00:00+00:00
[2024-08-16 11:14:19,932] {standard_task_runner.py:52} INFO - Started process 66452 to run task
[2024-08-16 11:14:19,934] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-29T00:00:00+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpofjgmuki', '--error-file', '/tmp/tmpetmmd4n8']
[2024-08-16 11:14:19,935] {standard_task_runner.py:80} INFO - Job 226: Subtask extract_clima_files
[2024-08-16 11:14:19,969] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:14:19,989] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 11:14:19,993] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240729T000000, start_date=20240816T141419, end_date=20240816T141419
[2024-08-16 11:14:20,012] {standard_task_runner.py:92} ERROR - Failed to execute job 226 for task extract_clima_files ('data_inteval_end' is undefined; 66452)
[2024-08-16 11:14:20,027] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 11:14:20,041] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:19:24,426] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-08-16 11:19:24,433] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-08-16 11:19:24,433] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:24,434] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:19:24,434] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:24,452] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-29 00:00:00+00:00
[2024-08-16 11:19:24,455] {standard_task_runner.py:52} INFO - Started process 69461 to run task
[2024-08-16 11:19:24,459] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-29T00:00:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpdxwcipsg', '--error-file', '/tmp/tmp51skr3d5']
[2024-08-16 11:19:24,460] {standard_task_runner.py:80} INFO - Job 228: Subtask extract_clima_files
[2024-08-16 11:19:24,497] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:19:24,556] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-07-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-29T00:00:00+00:00
[2024-08-16 11:19:24,557] {logging_mixin.py:115} INFO - 2024-08-05
[2024-08-16 11:19:25,193] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:19:25,200] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240729T000000, start_date=20240816T141924, end_date=20240816T141925
[2024-08-16 11:19:25,241] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:19:25,259] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:22:25,395] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-08-16 11:22:25,399] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [queued]>
[2024-08-16 11:22:25,400] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:25,400] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:22:25,400] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:25,407] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-29 00:00:00+00:00
[2024-08-16 11:22:25,410] {standard_task_runner.py:52} INFO - Started process 73274 to run task
[2024-08-16 11:22:25,413] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-29T00:00:00+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmptmlhgwu1', '--error-file', '/tmp/tmpamydwu6v']
[2024-08-16 11:22:25,413] {standard_task_runner.py:80} INFO - Job 230: Subtask extract_clima_files
[2024-08-16 11:22:25,443] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-29T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:22:25,476] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-07-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-29T00:00:00+00:00
[2024-08-16 11:22:25,476] {logging_mixin.py:115} INFO - 2024-08-05
[2024-08-16 11:22:26,131] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:22:26,137] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240729T000000, start_date=20240816T142225, end_date=20240816T142226
[2024-08-16 11:22:26,154] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:22:26,166] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
