[2024-08-16 10:58:21,116] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [queued]>
[2024-08-16 10:58:21,122] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [queued]>
[2024-08-16 10:58:21,122] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:58:21,122] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 10:58:21,122] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:58:21,136] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-08-05 00:00:00+00:00
[2024-08-16 10:58:21,142] {standard_task_runner.py:52} INFO - Started process 59362 to run task
[2024-08-16 10:58:21,147] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-08-05T00:00:00+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmprpkcdiuk', '--error-file', '/tmp/tmp56hdx663']
[2024-08-16 10:58:21,148] {standard_task_runner.py:80} INFO - Job 205: Subtask extract_clima_files
[2024-08-16 10:58:21,213] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 10:58:21,247] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 10:58:21,255] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240805T000000, start_date=20240816T135821, end_date=20240816T135821
[2024-08-16 10:58:21,271] {standard_task_runner.py:92} ERROR - Failed to execute job 205 for task extract_clima_files ('data_inteval_end' is undefined; 59362)
[2024-08-16 10:58:21,291] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 10:58:21,304] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:14:21,643] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [queued]>
[2024-08-16 11:14:21,649] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [queued]>
[2024-08-16 11:14:21,649] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:21,650] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:14:21,650] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:21,664] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-08-05 00:00:00+00:00
[2024-08-16 11:14:21,666] {standard_task_runner.py:52} INFO - Started process 66465 to run task
[2024-08-16 11:14:21,669] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-08-05T00:00:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpvy2idkrk', '--error-file', '/tmp/tmp_pdw0302']
[2024-08-16 11:14:21,669] {standard_task_runner.py:80} INFO - Job 227: Subtask extract_clima_files
[2024-08-16 11:14:21,699] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:14:21,720] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 11:14:21,725] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240805T000000, start_date=20240816T141421, end_date=20240816T141421
[2024-08-16 11:14:21,734] {standard_task_runner.py:92} ERROR - Failed to execute job 227 for task extract_clima_files ('data_inteval_end' is undefined; 66465)
[2024-08-16 11:14:21,762] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 11:14:21,776] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:19:26,977] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [queued]>
[2024-08-16 11:19:26,981] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [queued]>
[2024-08-16 11:19:26,982] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:26,982] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:19:26,982] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:26,991] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-08-05 00:00:00+00:00
[2024-08-16 11:19:26,994] {standard_task_runner.py:52} INFO - Started process 69510 to run task
[2024-08-16 11:19:26,996] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-08-05T00:00:00+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp5xgdczri', '--error-file', '/tmp/tmpuw1jle4w']
[2024-08-16 11:19:26,997] {standard_task_runner.py:80} INFO - Job 229: Subtask extract_clima_files
[2024-08-16 11:19:27,032] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:19:27,070] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-08-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-05T00:00:00+00:00
[2024-08-16 11:19:27,071] {logging_mixin.py:115} INFO - 2024-08-12
[2024-08-16 11:19:27,778] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:19:27,786] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240805T000000, start_date=20240816T141926, end_date=20240816T141927
[2024-08-16 11:19:27,824] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:19:27,840] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:22:27,631] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [queued]>
[2024-08-16 11:22:27,635] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [queued]>
[2024-08-16 11:22:27,635] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:27,635] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:22:27,635] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:27,643] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-08-05 00:00:00+00:00
[2024-08-16 11:22:27,645] {standard_task_runner.py:52} INFO - Started process 73303 to run task
[2024-08-16 11:22:27,648] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-08-05T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpge_1ca1p', '--error-file', '/tmp/tmp_owi63gp']
[2024-08-16 11:22:27,648] {standard_task_runner.py:80} INFO - Job 231: Subtask extract_clima_files
[2024-08-16 11:22:27,680] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-08-05T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:22:27,715] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-08-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-05T00:00:00+00:00
[2024-08-16 11:22:27,716] {logging_mixin.py:115} INFO - 2024-08-12
[2024-08-16 11:22:28,384] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:22:28,390] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240805T000000, start_date=20240816T142227, end_date=20240816T142228
[2024-08-16 11:22:28,429] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:22:28,440] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
