[2024-08-16 10:57:59,505] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-08-16 10:57:59,513] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-08-16 10:57:59,513] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:57:59,513] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 10:57:59,513] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 10:57:59,527] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-01 00:00:00+00:00
[2024-08-16 10:57:59,531] {standard_task_runner.py:52} INFO - Started process 58958 to run task
[2024-08-16 10:57:59,537] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp871ao_4_', '--error-file', '/tmp/tmph81p_l_g']
[2024-08-16 10:57:59,543] {standard_task_runner.py:80} INFO - Job 196: Subtask extract_clima_files
[2024-08-16 10:57:59,685] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 10:57:59,749] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 10:57:59,753] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240701T000000, start_date=20240816T135759, end_date=20240816T135759
[2024-08-16 10:57:59,768] {standard_task_runner.py:92} ERROR - Failed to execute job 196 for task extract_clima_files ('data_inteval_end' is undefined; 58958)
[2024-08-16 10:57:59,796] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 10:57:59,820] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:14:04,815] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-08-16 11:14:04,819] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-08-16 11:14:04,819] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:04,819] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:14:04,819] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:14:04,832] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-01 00:00:00+00:00
[2024-08-16 11:14:04,835] {standard_task_runner.py:52} INFO - Started process 66165 to run task
[2024-08-16 11:14:04,838] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmppye4bv7o', '--error-file', '/tmp/tmpqcvdzmeo']
[2024-08-16 11:14:04,838] {standard_task_runner.py:80} INFO - Job 218: Subtask extract_clima_files
[2024-08-16 11:14:04,869] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:14:04,887] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in render_template
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 404, in <dictcomp>
    return {key: self.render_template(value, context, jinja_env) for key, value in value.items()}
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2024-08-16 11:14:04,892] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240701T000000, start_date=20240816T141404, end_date=20240816T141404
[2024-08-16 11:14:04,901] {standard_task_runner.py:92} ERROR - Failed to execute job 218 for task extract_clima_files ('data_inteval_end' is undefined; 66165)
[2024-08-16 11:14:04,931] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-16 11:14:04,948] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:19:06,416] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-08-16 11:19:06,421] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-08-16 11:19:06,421] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:06,421] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:19:06,421] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:19:06,428] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-01 00:00:00+00:00
[2024-08-16 11:19:06,432] {standard_task_runner.py:52} INFO - Started process 69154 to run task
[2024-08-16 11:19:06,435] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpx8tjyu_y', '--error-file', '/tmp/tmp6zf2ldbo']
[2024-08-16 11:19:06,435] {standard_task_runner.py:80} INFO - Job 220: Subtask extract_clima_files
[2024-08-16 11:19:06,490] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:19:06,543] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-01T00:00:00+00:00
[2024-08-16 11:19:06,544] {logging_mixin.py:115} INFO - 2024-07-08
[2024-08-16 11:19:07,251] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:19:07,258] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240701T000000, start_date=20240816T141906, end_date=20240816T141907
[2024-08-16 11:19:07,308] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:19:07,334] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16 11:22:08,206] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-08-16 11:22:08,212] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-08-16 11:22:08,212] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:08,212] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-16 11:22:08,212] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-16 11:22:08,220] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extract_clima_files> on 2024-07-01 00:00:00+00:00
[2024-08-16 11:22:08,224] {standard_task_runner.py:52} INFO - Started process 72923 to run task
[2024-08-16 11:22:08,226] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'clima_process_extractor', 'extract_clima_files', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp3ckrq2xt', '--error-file', '/tmp/tmp3xxufci1']
[2024-08-16 11:22:08,227] {standard_task_runner.py:80} INFO - Job 222: Subtask extract_clima_files
[2024-08-16 11:22:08,267] {task_command.py:370} INFO - Running <TaskInstance: clima_process_extractor.extract_clima_files scheduled__2024-07-01T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-16 11:22:08,309] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=clima_process_extractor
AIRFLOW_CTX_TASK_ID=extract_clima_files
AIRFLOW_CTX_EXECUTION_DATE=2024-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-01T00:00:00+00:00
[2024-08-16 11:22:08,309] {logging_mixin.py:115} INFO - 2024-07-08
[2024-08-16 11:22:09,016] {python.py:173} INFO - Done. Returned value was: None
[2024-08-16 11:22:09,020] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=clima_process_extractor, task_id=extract_clima_files, execution_date=20240701T000000, start_date=20240816T142208, end_date=20240816T142209
[2024-08-16 11:22:09,045] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-16 11:22:09,058] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
